// Generated by IB v0.2.4 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>


@interface OpzioniController : UIViewController

@property IBOutlet UIScrollView * scroller;
@property IBOutlet id btn_kill;
@property IBOutlet id label_username;
@property (unsafe_unretained, nonatomic) IBOutlet UIBarButtonItem *menu_btn;


-(IBAction) viewDidLoad;
-(IBAction) kill_app:(id) sender;
-(IBAction) showActionSheet:(id) sender;

@end






